// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectLapDay2.Models;

#nullable disable

namespace ProjectLapDay2.Migrations
{
    [DbContext(typeof(Day2DBContext))]
    [Migration("20221108164025_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectLapDay2.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Dependant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("Emp_id")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Emp_id");

                    b.ToTable("Dependants");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("dept_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("departmentid")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("departmentid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.WorkOn", b =>
                {
                    b.Property<int>("Pid")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Eid")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("hours")
                        .HasColumnType("int");

                    b.HasKey("Pid", "Eid");

                    b.HasIndex("Eid");

                    b.ToTable("WorkOn");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Dependant", b =>
                {
                    b.HasOne("ProjectLapDay2.Models.Employee", "Emp")
                        .WithMany("depend")
                        .HasForeignKey("Emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Employee", b =>
                {
                    b.HasOne("ProjectLapDay2.Models.Department", "dept")
                        .WithMany("emp")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dept");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Project", b =>
                {
                    b.HasOne("ProjectLapDay2.Models.Department", "department")
                        .WithMany("proj")
                        .HasForeignKey("departmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.WorkOn", b =>
                {
                    b.HasOne("ProjectLapDay2.Models.Employee", "Emp")
                        .WithMany("WorkOns")
                        .HasForeignKey("Eid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLapDay2.Models.Project", "Proj")
                        .WithMany("worksfor")
                        .HasForeignKey("Pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");

                    b.Navigation("Proj");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Department", b =>
                {
                    b.Navigation("emp");

                    b.Navigation("proj");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Employee", b =>
                {
                    b.Navigation("WorkOns");

                    b.Navigation("depend");
                });

            modelBuilder.Entity("ProjectLapDay2.Models.Project", b =>
                {
                    b.Navigation("worksfor");
                });
#pragma warning restore 612, 618
        }
    }
}
